name: My Job

on:
  workflow_dispatch:
  workflow_call:

jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Something safe
        run: echo "Hello, world!"
